version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '04:00'
    open-pull-requests-limit: 5
    rebase-strategy: 'auto'
    versioning-strategy: 'increase'
    allow:
      - dependency-type: 'all'
    ignore:
      - dependency-name: 'pnpm'
